### ISSUE TITLE
Export domain should be created following creating a data domain.

### ISSUE THREAD

**Issue by mgoldboi** [machacekondra/ovirt-ansible-roles#1]
currently playbook is failing on first run due to it.
TASK [ovirt-infra : Add storages] *********************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: -Please attach Data Domain to the Data Center first.]". HTTP response code is 409.
failed: [engine] (item={'key': u'templates', 'value': {u'domain_function': u'export', u'nfs': {u'path': u'/nfs_data/export', u'version': u'v3', u'address': u'nfs'}}}) => {"failed": true, "item": {"key": "templates", "value": {"domain_function": "export", "nfs": {"address": "nfs", "path": "/nfs_data/export", "version": "v3"}}}, "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot attach Storage Domain.\n-Please attach Data Domain to the Data Center first.]\". HTTP response code is 409."}

**Comment by machacekondra** [comment]
Fixed by: https://github.com/machacekondra/ovirt-ansible-roles/commit/e1dec6f01b94ac929636f35f6463625848f98a17
